/**
 * Suprepto object library — static registry mirror (issue #34).
 *
 * Mirrors scientific/registry builtin_* metadata (single source of truth:
 * GET /api/ir/schema; the server list wins when available).
 */

export const CATEGORY_META = {
  core: { label: 'Basic', icon: '◻' },
  ui: { label: 'UI / Layout', icon: '▤' },
  math: { label: 'Mathematics', icon: '∑' },
  graph: { label: 'Graphs & Networks', icon: '⬡' },
  nn: { label: 'Neural / AI', icon: '◉' },
  biology: { label: 'Biology', icon: '🧬' },
  kinematics: { label: 'Geometry & Kinematics', icon: '⌖' },
  attention: { label: 'Attention', icon: '⇄' },
  presentation: { label: 'Presentation', icon: '▤' },
  comparison: { label: 'Comparison', icon: '⇋' }
}

/** Creation presets: pre-filled properties + suggested timeline steps. */
export const PRESETS = {
  'math.formula': { properties: { source: 'E = mc^2', fontSize: 44 },
    expression: { source: 'E = mc^2', terms: {}, bindings: {} } },
  'math.matrix': { properties: { rows: [[1, 0], [0, 1]], heat: false } },
  'math.tensor': { properties: { shape: [2, 3, 2], heat: true } },
  'math.vector': { properties: { components: [2, 1] } },
  'math.distribution': { properties: { kind: 'normal', mu: 0, sigma: 1 } },
  'math.axes': { properties: { xMin: -3, xMax: 3, yMin: -2, yMax: 2 } },
  'graph.network': {
    properties: { nodes: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' },
      { id: 'c', label: 'C' }],
      edges: [{ from: 'a', to: 'b', weight: 0.7 },
              { from: 'b', to: 'c', weight: 1.0 }],
      layout: 'circle', directed: false, showWeights: true } },
  'presentation.title': { properties: { text: 'Title', subtitle: '',
    fontSize: 40 } },
  'presentation.metric_card': { properties: { title: 'metric',
    provider: 'x', format: '{value:.2f}', live: true } },
  'presentation.table': { properties: { headers: ['A', 'B'],
    rows: [['1', '2']] } },
  'nn.network': { properties: { layers: [4, 6, 1], seed: 11 } },
  'attention.matrix': { properties: { queries: [0, 1, 2],
    keys: [0, 1, 2] } },
  'biology.protein': { properties: { residues: 24, seed: 7,
    representation: 'cartoon' } },
  'kinematics.torus': { properties: { majorRadius: 2.2,
    minorRadius: 0.8 } }
}

export const CORE_LIBRARY = [
  ['core.group', 'Group', 'core', '2d', 'Logical grouping container.', {}],
  ['text.label', 'Text Label', 'core', '2d', 'Editable text/caption.',
    { text: 'Label', fontSize: 28 }],
  ['ui.panel', 'Panel', 'ui', '2d', 'Rounded background panel.',
    { width: 6, height: 3 }],
  ['ui.grid', 'Grid', 'ui', '2d', 'Cell layout grid.',
    { columns: 4, rows: 3 }],
  ['ui.badge', 'Badge', 'ui', '2d', 'Colored pill (scores, tags).',
    { text: 'OK', tone: 'ok' }],
  ['ui.stamp', 'Validation Stamp', 'ui', '2d', 'OK/FAIL verdict stamp.',
    { verdict: 'ok' }],
  ['math.formula', 'Formula', 'math', '2d',
    'Structured LaTeX expression with terms/bindings.', {}],
  ['math.axes', 'Axes', 'math', '2d', 'Coordinate axes.', {}],
  ['math.curve', 'Curve', 'math', '2d', 'Function curve y=f(x).',
    { function: 'x', color: 'accent' }],
  ['math.point', 'Point on Axes', 'math', '2d', 'Dot at (x, f(x)).',
    { x: 1 }],
  ['math.region', 'Region / Interval', 'math', '2d',
    'Shaded region on axes.', { xMin: 0, xMax: 1 }],
  ['math.vector', 'Vector', 'math', '2d', 'Arrow vector.', {}],
  ['math.matrix', 'Matrix', 'math', '2d', 'Numeric matrix with heat map.',
    {}],
  ['math.tensor', 'Tensor View', 'math', '2d', 'N-d tensor cells.', {}],
  ['math.number_line', 'Number Line', 'math', '2d', '1D axis.', {}],
  ['math.distribution', 'Distribution', 'math', '2d',
    'Probability pdf curve.', {}],
  ['graph.network', 'Graph / Network', 'graph', '2d',
    'Semantic graph: nodes, edges, weights, layouts.', {}],
  ['graph.state_chart', 'State Chart', 'graph', '2d',
    'Visual chart of a declared machine.', {}],
  ['nn.network', 'Neural Network', 'nn', '2d',
    'Deterministic MLP with live activations.', {}],
  ['attention.matrix', 'Attention Heatmap', 'attention', '2d',
    'Query-key score matrix.', {}],
  ['attention.link', 'Attention Link', 'attention', '3d',
    'Live weighted edge.', { fromId: '', toId: '' }],
  ['attention.frame', 'Orientation Frame', 'attention', '3d',
    'SO(3) triad anchor.', {}],
  ['biology.protein', 'Protein Structure', 'biology', '2d',
    'Residue-level protein.', {}],
  ['biology.sequence', 'Sequence', 'biology', '2d',
    'Amino-acid strip.', { sequence: 'MKTLLILAVVAA' }],
  ['kinematics.torus', 'Flat Torus Flow', 'kinematics', '3d',
    'T^2 manifold with flow.', {}],
  ['kinematics.chain', 'PoE Kinematic Chain', 'kinematics', '3d',
    'Serial revolute chain.', { thetas: [0.3, 0.5] }],
  ['kinematics.jacobian', 'Jacobian Arrows', 'kinematics', '3d',
    'Jacobian columns at end effector.', {}],
  ['kinematics.obstacle', 'Obstacle', 'kinematics', '3d',
    'Spherical obstacle.', { center: [1, 0.5, 0] }],
  ['presentation.title', 'Title', 'presentation', '2d',
    'Scene title + subtitle.', {}],
  ['presentation.callout', 'Callout', 'presentation', '2d',
    'Labeled pointer to a target.', { text: 'note' }],
  ['presentation.legend', 'Legend', 'presentation', '2d',
    'Color/label entries.', { entries: [{ label: 'A', color: 'accent' }] }],
  ['presentation.table', 'Table', 'presentation', '2d',
    'Text table with live cells.', {}],
  ['presentation.metric_card', 'Metric Card', 'presentation', '2d',
    'Live metric bound to a state symbol.', {}],
  ['comparison.panel', 'Comparison Panel', 'comparison', '2d',
    'Comparison-driven panel.', {}],
  ['hud.fixed', 'Fixed HUD', 'presentation', '2d',
    'Camera-independent HUD.', { text: 'HUD' }]
]
