"""Scene 'sample_scene' — generated by Manim Studio (sci-ir/1).

Deterministic export: identical IR produces identical source.
Round-trips through scientific.export.import_document().
"""

from scientific import DataRef, Derived, Literal, ScientificScene, Symbol
from scientific.manim_adapter import BaseScientificScene


def build() -> ScientificScene:
    scene = ScientificScene(
        "sample_scene",
        title="Sample",
        scene_type="scene_2d",
        camera=None,
    )
    scene.node("ui.panel", "panel", height=3, title="Panel", width=6, position=[-2.5, 1, 0])
    scene.node("text.label", "caption", fontSize=24, text="hello", position=[-2.5, 2.6, 0])
    scene.formula("eq", source="tau = J(theta).T @ F", terms={"Jt": "J(theta).T"}, bindings={"theta": {"kind": "literal", "value": 0.6}}, highlights=["J(theta).T"], fontSize=40, position=[2, -0.5, 0])
    scene.live_value("energy", {"expr": "a * b + 1", "inputs": {"a": {"kind": "literal", "value": 2}, "b": {"kind": "literal", "value": 3}}, "kind": "derived"}, format="E = {value:.2f}")
    scene.bind("theta", {"kind": "literal", "value": 0.6})
    scene.relationship("panel", "eq", color="accent", id="link", kind="arrow", live=True)
    with scene.stage(stage_id="s1", title="Intro") as st:
        st.show("panel")
        st.play("eq", "write", duration=1.5)
        st.highlight("eq", color="warn", duration=1)
        st.annotate("panel", "E = {energy}", duration=1)
        st.camera({"zoom": 0.85}, duration=2)
        st.transform("panel", {"width": 7}, duration=1.2)
        st.custom("print('custom code preserved')")
    return scene


class SampleScene(BaseScientificScene):
    """Rendered from sci-ir/1 scene 'sample_scene'."""

    def get_scene(self) -> ScientificScene:
        return build()

if __name__ == "__main__":
    from scientific.run import main
    main([__file__])
