"""Scene 'suprepto_demo' — generated by Manim Studio (sci-ir/1).

Deterministic export: identical IR produces identical source.
Round-trips through scientific.export.import_document().
"""

from scientific import DataRef, Derived, Literal, ScientificScene, Symbol
from scientific.manim_adapter import BaseScientificScene


def build() -> ScientificScene:
    scene = ScientificScene(
        "suprepto_demo",
        title="Suprepto Demo",
        scene_type="scene_2d",
        camera=None,
    )
    scene.node("ui.panel", "stage_panel", height=2.5, width=5)
    scene.node("presentation.metric_card", "readout", format="{value:.1f}", provider="x", title="x", position=[2.2, 1.2, 0])
    scene.node("graph.network", "graph", edges=[{"from": "a", "to": "b", "weight": 0.7}, {"directed": True, "from": "b", "to": "c", "weight": 1}], layout="circle", nodes=[{"id": "a", "label": "A"}, {"color": "accent2", "id": "b", "label": "B"}, {"id": "c", "label": "C"}], position=[0, -1.8, 0])
    scene.state("x", keyframes=[[0, 0], [2, 10]], easing="linear", value=0)
    scene.derive("speed", expr="x / 2", inputs={"x": "x"})
    scene.machine("gd", states=[{"id": "initial", "label": "Initial"}, {"id": "updated", "label": "Updated"}], transitions=[{"id": "t1", "sets": {"x": 4}, "source": "initial", "target": "updated", "trigger": "step"}], initial="initial")
    scene.compare("cmp", kind="before_after", metrics=[{"a": 1, "b": 2.5, "deltaFormat": "{delta:+.2f}", "format": "{value}", "label": "score"}], title="Score change")
    scene.annotate("stage_panel", provider="speed", format="v = {value:.2f}", id="live_speed")
    with scene.stage(stage_id="run", title="Run") as st:
        st.show("stage_panel")
        st.interpolate("x", to=10, duration=2)
        st.set("x", 3)
        st.transition("gd", to="updated", duration=1)
        st.compare("cmp", duration=2)
        st.highlight("graph", behaviors=["focus", "dim_others"], color="warn", duration=1)
        st.custom("print('suprepto boundary')")
    return scene


class SupreptoDemo(BaseScientificScene):
    """Rendered from sci-ir/1 scene 'suprepto_demo'."""

    def get_scene(self) -> ScientificScene:
        return build()

if __name__ == "__main__":
    from scientific.run import main
    main([__file__])
