"""Scene 'torus_demo' — generated by Manim Studio (sci-ir/1).

Deterministic export: identical IR produces identical source.
Round-trips through scientific.export.import_document().
"""

from scientific import DataRef, Derived, Literal, ScientificScene, Symbol
from scientific.manim_adapter import ThreeDScientificScene


def build() -> ScientificScene:
    scene = ScientificScene(
        "torus_demo",
        title="Torus Demo",
        scene_type="three_d",
        camera={"distance": 11, "phi": 70, "theta": -40},
    )
    scene.node("kinematics.torus", "torus", dt=0.045, majorRadius=2.4, minorRadius=0.85, steps=80, space="world3d")
    scene.node("kinematics.chain", "chain", linkLength=0.9, thetas=[0.9, -0.55, 0.35, 0.15], space="world3d", position=[2.2, 0, 0])
    scene.node("kinematics.obstacle", "obstacle", center=[1.85, 0.75, 0.45], radius=0.72, space="world3d")
    scene.live_value("hero", {"key": "energy", "kind": "data", "ref": "synth/protein.json"}, format="ΔG = {value:.2f}")
    with scene.stage(stage_id="flow", title="Flow") as st:
        st.play("torus", "create", duration=2)
        st.camera({"orbit": 0.18}, duration=3.2)
    return scene


class TorusDemo(ThreeDScientificScene):
    """Rendered from sci-ir/1 scene 'torus_demo'."""

    def get_scene(self) -> ScientificScene:
        return build()

if __name__ == "__main__":
    from scientific.run import main
    main([__file__])
