"""Scene 'torus_demo' — generated by Manim Studio (sci-ir/1).

Deterministic export: identical IR produces identical source.
Round-trips through scientific.export.import_document().
"""

from scientific import DataRef, Derived, Literal, ScientificScene, Symbol
from scientific.manim_adapter import ThreeDScientificScene


def build() -> ScientificScene:
    scene = ScientificScene(
        "torus_demo",
        title="Torus Demo",
        scene_type="three_d",
        camera={"phi": 70, "theta": -40},
    )
    scene.node("kinematics.torus", "torus", dt=0.045, majorRadius=2.2, minorRadius=0.8, steps=90)
    scene.node("kinematics.chain", "chain", linkLength=0.9, thetas=[0.3, 0.5, 0.2])
    scene.node("kinematics.jacobian", "jac", position=[0, 0, 0], scale=0.55)
    scene.node("kinematics.obstacle", "obstacle", center=[1, 0.5, 0.3], radius=0.55)
    with scene.stage(stage_id="flow", title="Flow") as st:
        st.show("torus")
        st.play("chain", "create", duration=2)
        st.highlight("chain", color="warn", duration=1)
    return scene


class TorusDemo(ThreeDScientificScene):
    """Rendered from sci-ir/1 scene 'torus_demo'."""

    def get_scene(self) -> ScientificScene:
        return build()

if __name__ == "__main__":
    from scientific.run import main
    main([__file__])
