"""Scene 'wall_demo' — generated by Manim Studio (sci-ir/1).

Deterministic export: identical IR produces identical source.
Round-trips through scientific.export.import_document().
"""

from scientific import DataRef, Derived, Literal, ScientificScene, Symbol
from scientific.manim_adapter import MovingCameraScientificScene


def build() -> ScientificScene:
    scene = ScientificScene(
        "wall_demo",
        title="Wall Demo",
        scene_type="moving_camera",
        camera={"backgroundColor": "bg", "zoom": 0.92},
    )
    scene.node("ui.grid", "wall", cellWidth=1.5, columns=4, gap=0.24, rows=3)
    scene.node("ui.panel", "banner", height=1.1, width=10, position=[0, 3.4, 0])
    scene.node("ui.stamp", "stamp_1", verdict="ok", position=[1, -1, 0])
    scene.node("nn.network", "scorer", layers=[4, 6, 1], seed=11)
    scene.live_value("hero_energy", {"key": "energy", "kind": "data", "ref": "synth/protein.json"}, format="ΔG = {value:.2f} kcal/mol")
    with scene.stage(stage_id="intro", title="The Wall") as st:
        st.show("wall")
        st.play("banner", "fade_in", duration=1.2)
    return scene


class WallDemo(MovingCameraScientificScene):
    """Rendered from sci-ir/1 scene 'wall_demo'."""

    def get_scene(self) -> ScientificScene:
        return build()

if __name__ == "__main__":
    from scientific.run import main
    main([__file__])
