"""Deterministic IR -> Python exporter.

Emits a standalone, runnable scene file that rebuilds the exact same IR via
the public authoring API.  The output is byte-stable: identical documents
produce identical source (no timestamps, no random ordering).  Custom steps
are preserved verbatim as ``st.custom(...)`` calls.

The JS mirror (services/api/src/ir/emitPython.js) must produce byte-identical
output — enforced by golden-fixture parity tests.
"""

from __future__ import annotations

from ..ir.document import SceneDocument
from .emitter_parts import emit_expr, emit_node, emit_step
from .emitter_state import emit_state_sections
from .literals import py_literal

BASE_CLASSES = {
    "scene_2d": "BaseScientificScene",
    "moving_camera": "MovingCameraScientificScene",
    "three_d": "ThreeDScientificScene",
    "custom": "BaseScientificScene",
}


def scene_class_name(document_id: str) -> str:
    return "".join(part.capitalize()
                   for part in str(document_id).split("_") if part)


def emit(document: SceneDocument) -> str:
    lines: list[str] = []
    w = lines.append
    base = BASE_CLASSES.get(document.scene_type, "BaseScientificScene")
    w(f'"""Scene {document.id!r} — generated by Manim Studio (sci-ir/1).')
    w("")
    w("Deterministic export: identical IR produces identical source.")
    w('Round-trips through scientific.export.import_document().')
    w('"""')
    w("")
    w("from scientific import DataRef, Derived, Literal, ScientificScene, Symbol")
    w(f"from scientific.manim_adapter import {base}")
    w("")
    w("")
    w("def build() -> ScientificScene:")
    w(f"    scene = ScientificScene(")
    w(f"        {py_literal(document.id)},")
    w(f"        title={py_literal(document.title)},")
    w(f"        scene_type={py_literal(document.scene_type)},")
    w(f"        camera={py_literal(document.camera) if document.camera else 'None'},")
    w(f"    )")
    _emit_objects(w, document)
    emit_state_sections(w, document)
    for value in document.values.values():
        w(f"    scene.live_value({py_literal(value.id)}, "
          f"{py_literal(value.source)}, format={py_literal(value.format)})")
    for symbol in sorted(document.bindings):
        source = document.bindings[symbol]
        w(f"    scene.bind({py_literal(symbol)}, {py_literal(source)})")
    for rel in document.relationships.values():
        srcs = ", ".join(py_literal(s) for s in rel.sources)
        props = ", ".join(f"{k}={py_literal(v)}"
                          for k, v in sorted(rel.properties.items()))
        tail = f", {props}" if props else ""
        w(f"    scene.relationship({srcs}{tail}, id={py_literal(rel.id)}, "
          f"kind={py_literal(rel.kind)}, live={py_literal(rel.live)})")
    for stage in document.timeline:
        w(f"    with scene.stage(stage_id={py_literal(stage.id)}, "
          f"title={py_literal(stage.title)}) as st:")
        if not stage.steps:
            w("        pass")
        for step in stage.steps:
            emit_step(w, step)
    w("    return scene")
    _emit_class(w, document, base)
    w("")
    w('if __name__ == "__main__":')
    w("    from scientific.run import main")
    w("    main([__file__])")
    w("")
    return "\n".join(lines)


def _emit_objects(w, document: SceneDocument) -> None:
    """Objects in document order (authoring order is semantic: z-order)."""
    emitted: set[str] = set()
    for node in document.objects.values():
        if node.id in document.expressions and node.type == "math.formula":
            emit_expr(w, document.expressions[node.id], node)
            emitted.add(node.id)
        else:
            emit_node(w, node)
    for expr_id in document.expressions:
        if expr_id not in emitted:
            emit_expr(w, document.expressions[expr_id], None)


def _emit_class(w, document: SceneDocument, base: str) -> None:
    name = scene_class_name(document.id)
    w("")
    w("")
    w(f"class {name}({base}):")
    w(f'    """Rendered from sci-ir/1 scene {document.id!r}."""')
    w("")
    w("    def get_scene(self) -> ScientificScene:")
    w("        return build()")
