/**
 * IR -> Python emitter — JS mirror of scientific/export/emitter{,_parts}.py.
 *
 * Byte-identical output with the Python emitter is enforced by golden
 * fixtures (services/api/tests/fixtures/ir/*.py).  Deterministic: identical
 * documents produce identical source on both sides.
 */

import { pyLiteral } from './literals.js';
import { emitStateSections } from './emitState.js';
import { emitStep } from './emitSteps.js';
import { emitNode, emitExpr } from './emitObjects.js';

const BASE_CLASSES = {
  scene_2d: 'BaseScientificScene',
  moving_camera: 'MovingCameraScientificScene',
  three_d: 'ThreeDScientificScene',
  custom: 'BaseScientificScene'
};

const KEYWORDS = new Set(['False', 'None', 'True', 'and', 'as', 'assert',
  'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif',
  'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import',
  'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return',
  'try', 'while', 'with', 'yield']);

/** Python repr() for simple strings (ids): single-quoted. */
function pyRepr (value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function isIdent (name) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !KEYWORDS.has(name);
}

function kwarg (k, v) {
  if (isIdent(k)) return `${k}=${pyLiteral(v)}`;
  return `**{${JSON.stringify(k)}: ${pyLiteral(v)}}`;
}

function sceneClassName (documentId) {
  return String(documentId).split('_')
    .filter((p) => p.length > 0)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function emitDocument (doc) {
  const lines = [];
  const w = (line) => lines.push(line);
  const base = BASE_CLASSES[doc.sceneType] || 'BaseScientificScene';
  w(`"""Scene ${pyRepr(doc.id)} — generated by Manim Studio (sci-ir/1).`);
  w('');
  w('Deterministic export: identical IR produces identical source.');
  w('Round-trips through scientific.export.import_document().');
  w('"""');
  w('');
  w('from scientific import DataRef, Derived, Literal, ScientificScene, ' +
    'Symbol');
  w(`from scientific.manim_adapter import ${base}`);
  w('');
  w('');
  w('def build() -> ScientificScene:');
  w('    scene = ScientificScene(');
  w(`        ${pyLiteral(doc.id)},`);
  w(`        title=${pyLiteral(doc.title)},`);
  w(`        scene_type=${pyLiteral(doc.sceneType)},`);
  w(`        camera=${doc.camera && Object.keys(doc.camera).length
    ? pyLiteral(doc.camera) : 'None'},`);
  w('    )');
  const expressions = doc.expressions || [];
  const expressionIds = new Set(expressions.map((e) => e.id));
  const emitted = new Set();
  for (const node of doc.objects || []) {
    if (expressionIds.has(node.id) && node.type === 'math.formula') {
      emitExpr(w, expressions.find((e) => e.id === node.id), node);
      emitted.add(node.id);
    } else {
      emitNode(w, node);
    }
  }
  for (const expr of expressions) {
    if (!emitted.has(expr.id)) emitExpr(w, expr, null);
  }
  emitStateSections(w, doc);
  for (const value of doc.values || []) {
    w(`    scene.live_value(${pyLiteral(value.id)}, ` +
      `${pyLiteral(value.source)}, format=${pyLiteral(value.format)})`);
  }
  for (const symbol of Object.keys(doc.bindings || {}).sort()) {
    w(`    scene.bind(${pyLiteral(symbol)}, ` +
      `${pyLiteral(doc.bindings[symbol])})`);
  }
  for (const rel of doc.relationships || []) {
    const srcs = (rel.sources || []).map((s) => pyLiteral(s)).join(', ');
    const props = Object.keys(rel.properties || {}).sort()
      .map((k) => `${k}=${pyLiteral(rel.properties[k])}`).join(', ');
    const tail = props ? `, ${props}` : '';
    w(`    scene.relationship(${srcs}${tail}, id=${pyLiteral(rel.id)}, ` +
      `kind=${pyLiteral(rel.kind)}, live=${pyLiteral(!!rel.live)})`);
  }
  for (const stage of doc.timeline || []) {
    w(`    with scene.stage(stage_id=${pyLiteral(stage.id)}, ` +
      `title=${pyLiteral(stage.title)}) as st:`);
    if (!stage.steps || stage.steps.length === 0) w('        pass');
    for (const step of stage.steps || []) emitStep(w, step);
  }
  w('    return scene');
  const name = sceneClassName(doc.id);
  w('');
  w('');
  w(`class ${name}(${base}):`);
  w(`    """Rendered from sci-ir/1 scene ${pyRepr(doc.id)}."""`);
  w('');
  w('    def get_scene(self) -> ScientificScene:');
  w('        return build()');
  w('');
  w('if __name__ == "__main__":');
  w('    from scientific.run import main');
  w('    main([__file__])');
  w('');
  return lines.join('\n');
}

export { emitDocument, sceneClassName, BASE_CLASSES };
export default emitDocument;
