/**
 * Scientific scene IR — JS mirror package.
 *
 * - schemaTypes.js: type metadata (drives validation + generic inspector)
 * - validate.js: document validation (verdict parity with Python)
 * - emitPython.js: deterministic IR -> Python (byte parity with Python)
 *
 * Parity is enforced by services/api/tests/ir.test.mjs against fixtures
 * generated by scripts/gen_parity_fixtures.py.
 */

export { TYPES, byKey, typeEntry, describeTypes } from './schemaTypes.js';
export { validateDocument } from './validate.js';
export { emitDocument, sceneClassName, BASE_CLASSES } from './emitPython.js';
export { pyLiteral, formatFloat } from './literals.js';
